# generate_report.R

# Carregar pacotes
if (!require("rmarkdown")) install.packages("rmarkdown")
if (!require("knitr")) install.packages("knitr")

# Caminho de saída do PDF
output_file <- "Metadoon_Report.pdf"

# Cria arquivo temporário RMarkdown
rmd_file <- tempfile(fileext = ".Rmd")

# Conteúdo do RMarkdown
rmd_content <- '
---
title: "Metadoon Analysis Report"
output: pdf_document
fontsize: 11pt
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

# 🧬 Metadoon Analysis Summary

This report compiles the main outputs generated by the **Metadoon** pipeline for amplicon data analysis (16S). It includes taxonomic profiles, diversity analyses, core microbiome heatmaps, and statistical tests such as PERMANOVA.

## 📂 Directory Overview

All plots and results are stored in the `Output/` directory automatically created during the execution of the pipeline.

## 🔍 Alpha Diversity

```{r}
alpha_imgs <- list.files("Output", pattern = "^alpha_diversity_.*\\.png$", full.names = TRUE)
lapply(alpha_imgs, knitr::include_graphics)
```

### 🧠 How to interpret alpha diversity
- **Observed**: Simple count of taxa present (richness).
- **Chao1 / ACE**: Estimated richness accounting for rare taxa.
- **Shannon**: Diversity considering both richness and evenness; higher values indicate more even communities.
- **Simpson**: Probability that two randomly chosen individuals belong to the same species; lower values suggest higher diversity.

Use alpha diversity metrics to compare richness and evenness across samples or groups.

## 🌱 Relative Abundance

```{r}
abund_imgs <- list.files("Output", pattern = "^abundance_.*\\.png$", full.names = TRUE)
lapply(abund_imgs, knitr::include_graphics)
```

### 🧠 How to interpret relative abundance
- Highlights dominant taxa at different taxonomic ranks.
- Look for shifts in abundance patterns between experimental groups or treatments.
- The "Others" category groups less abundant taxa to simplify visualization.

## 🔬 Core Microbiome Heatmaps

```{r}
core_imgs <- list.files("Output", pattern = "core_microbiome.*\\.png$", full.names = TRUE)
lapply(core_imgs, knitr::include_graphics)
```

### 🧠 How to interpret core microbiome heatmaps
- Shows which taxa are consistently present across samples.
- Prevalence = frequency of occurrence; Detection threshold = minimum abundance.
- Core taxa are potential biomarkers or ecologically important members.

## 🔄 Beta Diversity (NMDS)

```{r}
nmds_imgs <- list.files("Output", pattern = "^beta_diversity_NMDS_.*\\.png$", full.names = TRUE)
lapply(nmds_imgs, knitr::include_graphics)
```

### 🧠 How to interpret beta diversity (NMDS)
- NMDS visualizes dissimilarities in community structure between samples.
- Close points = similar composition; distant points = different communities.
- Ellipses group samples by metadata (e.g., treatment).
- Ideal for detecting clustering by environmental or experimental variables.

## 📊 PERMANOVA Results

```{r}
perm_files <- list.files("Output", pattern = "^permanova_result_.*\\.txt$", full.names = TRUE)
for (f in perm_files) {
  cat("###", basename(f), "\\n\\n")
  cat(readLines(f), sep = "\\n")
  cat("\\n\\n")
}
```

### 🧠 How to interpret PERMANOVA
- Tests whether microbial communities differ significantly between groups.
- A **p-value < 0.05** suggests significant differences.
- Use in combination with NMDS plots for stronger interpretation.
'

# Escreve conteúdo no .Rmd
writeLines(rmd_content, con = rmd_file)

# Renderiza o PDF
rmarkdown::render(input = rmd_file, output_file = output_file)

cat("✅ Relatório gerado em:", normalizePath(output_file), "\n")